# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
submit_for_review(true)
skip_metadata(true)
skip_screenshots(true)
ipa("../build/ios/ipa/conduit.ipa")
