# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
submit_for_review(true)
skip_metadata(false)
release_notes({
  'default' => "https://github.com/cogwheel0/conduit/releases/tag/v2.2.3",
})
skip_screenshots(true)
run_precheck_before_submit(false)
ipa("../build/ios/ipa/conduit.ipa")