# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Push a new release build to the Google Play"
  lane :release do
    upload_to_play_store(
    json_key_data: ENV['FASTLANE_JSON_KEY']
    track: 'production',
    aab: '../build/app/outputs/bundle/release/app-release.aab'
  )
  end
